function [fitresult, gof] = fitSin(t2, curData,plotIt)
if ~exist('plotIt','var')
    plotIt = 0;
end
%CREATEFIT(T2,CURDATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t2
%      Y Output: curData
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Oct-2016 11:25:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t2, curData );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 1 -Inf];
opts.StartPoint = [3.54917392676983 1.09090909090909 -0.353723724695198];
opts.Upper = [Inf 1 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if plotIt
    % Plot fit with data.
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData );
    legend( h, 'curData vs. t2', 'untitled fit 1', 'Location', 'NorthEast' );
    % Label axes
    xlabel t2
    ylabel curData
    grid on
end

