function [fitresult, gof] = fitSpline(rho, densityXY, sm, plotFlag)
if ~exist('plotFlag','var')
    plotFlag = 0;
end
%CREATEFIT(RHO,DENSITYXY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : rho
%      Y Output: densityXY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2021 22:43:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( rho, densityXY );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
if exist('sm','var') && ~isempty(sm)
    opts.SmoothingParam = sm;
else
    opts.SmoothingParam = 0.8;
end

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if plotFlag
    % Plot fit with data.
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData );
    legend( h, 'densityXY vs. rho', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'rho', 'Interpreter', 'none' );
    ylabel( 'densityXY', 'Interpreter', 'none' );
    grid on
end

